"""Генератор pjsip_custom.conf для Altel SIP-транков.
Читает trunks.csv (не коммитится в git) и генерирует pjsip-конфиг.

Usage:
  cp trunks.csv.example trunks.csv
  # отредактировать trunks.csv, заполнив реальные пароли
  python -m scripts.generate_pjsip
"""

import csv
import os
from pathlib import Path

ASTERISK_DIR = Path(__file__).parent.parent
TRUNKS_CSV = ASTERISK_DIR / "trunks.csv"
OUTPUT_FILE = ASTERISK_DIR / "pjsip_custom.conf"

PJSIP_TEMPLATE = """;=== KuroTrack Altel SIP trunk for {phone} ===

[altel-{phone}-registration]
type = registration
outbound_auth = altel-{phone}-auth
server_uri = sip:{sip_server}
client_uri = sip:{phone}@{sip_server}
retry_interval = 60
forbidden_retry_interval = 600
expiration = 3600
transport = transport-udp
support_path = no

[altel-{phone}-auth]
type = auth
auth_type = userpass
username = {phone}
password = {password}

[altel-{phone}-aor]
type = aor
contact = sip:{sip_server}
qualify_frequency = 60

[altel-{phone}]
type = endpoint
aors = altel-{phone}-aor
outbound_auth = altel-{phone}-auth
context = kurotrack-inbound
from_user = {phone}
from_domain = {sip_server}
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
disallow = all
allow = alaw,ulaw,g729
transport = transport-udp

[altel-{phone}-identify]
type = identify
endpoint = altel-{phone}
match = {sip_server}
"""

IDENTIFY_IPS = """
;=== Altel trusted IPs (добавить в identify для всех транков) ===
; 217.76.70.8, 217.76.70.108
; 185.57.74.8, 185.57.74.108
; 212.96.77.188, 212.96.77.238
; 212.96.68.158, 212.96.68.168
"""


def main():
    if not TRUNKS_CSV.exists():
        print(f"Error: {TRUNKS_CSV} not found.")
        print(f"Copy trunks.csv.example to trunks.csv and fill in credentials.")
        return 1

    configs = []
    with open(TRUNKS_CSV) as f:
        reader = csv.DictReader(f)
        for row in reader:
            phone = row["phone"].strip()
            password = row["password"].strip()
            sip_server = row["sip_server"].strip()

            if password == "CHANGE_ME" or not password:
                print(f"Skipping {phone}: password not set")
                continue

            configs.append(
                PJSIP_TEMPLATE.format(
                    phone=phone, password=password, sip_server=sip_server
                )
            )

    if not configs:
        print("No trunks with valid credentials found.")
        return 1

    output = ";=== Generated by kurotrack/generate_pjsip.py ===\n"
    output += ";=== DO NOT EDIT MANUALLY — regenerate via script ===\n\n"
    output += "\n".join(configs)
    output += IDENTIFY_IPS

    OUTPUT_FILE.write_text(output)
    os.chmod(OUTPUT_FILE, 0o600)

    print(f"Generated {len(configs)} trunks -> {OUTPUT_FILE}")
    print()
    print("Next steps:")
    print("1. Copy pjsip_custom.conf to FreePBX server: /etc/asterisk/pjsip_custom.conf")
    print("2. Reload PJSIP: asterisk -rx 'pjsip reload'")
    print("3. Check registrations: asterisk -rx 'pjsip show registrations'")

    return 0


if __name__ == "__main__":
    exit(main())
