FROM node:22-alpine AS build

WORKDIR /app
COPY frontend/dashboard/package.json .
RUN npm install
COPY frontend/dashboard/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /var/www/dashboard
